# Generated by Django 3.2.7 on 2021-09-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Etudiant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_Prof',
            field=models.BooleanField(default=False),
        ),
    ]
