# Generated by Django 3.2.7 on 2021-09-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20210914_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annee',
            old_name='nom',
            new_name='nom_annee',
        ),
        migrations.RenameField(
            model_name='filiere',
            old_name='nom',
            new_name='nom_filiere',
        ),
        migrations.RenameField(
            model_name='groupe',
            old_name='nom',
            new_name='nom_grp',
        ),
    ]
