# Generated by Django 3.2.7 on 2021-09-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20210915_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='nom_annee',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='nom_filiere',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
    ]
