# Generated by Django 3.2.7 on 2021-09-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20210915_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='annee',
            name='nom_filiere',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
    ]
