# Generated by Django 3.2.7 on 2021-09-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_ispresent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IsPresent',
            new_name='Present',
        ),
    ]
