# Generated by Django 3.2.7 on 2021-09-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_auto_20210917_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presenting',
            old_name='present_date',
            new_name='presence_heure',
        ),
    ]
