# Generated by Django 3.2.7 on 2021-09-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_groupe_deriger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='prof',
        ),
    ]
